import { extendTheme } from '@chakra-ui/react'

export const theme = extendTheme({
  layerStyles: {
    rootBox: {
      mx: [
        '50px',
        '100px',
        '150px',
        '200px',
        '250px',
        '300px',
        '350px',
        '400px',
        '450px',
      ],
      mt: ['50px', '100px', '150px', '200px'],
      p: '10px',
      maxW: '100%',
      maxH: '100%',
      color: 'teal',
      borderWidth: '1px',
      borderRadius: 'xl',
      borderColor: 'Black',
      boxShadow: 'dark-lg',
    },
    answerBox: {
      bg: 'white',
      borderRadius: 'md',
      borderColor: 'green.100',
      borderWidth: '2px',
      color: 'Black',
      fontSize: ['15px', 'sm', 'md'],
      fontWeight: 'bold',
      _hover: {
        bgGradient: 'linear(to-r, green.200, teal.500)',
        color: 'white',
        boxShadow: 'dark-lg',
      },
      py: '10px',
      maxH: '100%',
      w: '450px',
      maxW: '100%',
      px: '4px',
    },
    button: {
      bgGradient: 'linear(to-r, green.200, teal.500)',
      borderWidth: '1px',
      borderRadius: 'xl',
      borderColor: 'Black',
      color: 'black',
      letterSpacing: 'wide',
      fontWeight: 'semibold',
      _hover: {
        bgGradient: 'linear(to-r, green.200, teal.200)',
        color: 'black',
        fontWeight: 'bold',
        boxShadow: 'dark-lg',
      },
      mr: ['2px', '6px', '10px'],
      h: '40px',
      maxH: '60px',
      my: '40px',
      w: ['50px', '100px', '150px', '200px', '250px'],
    },
  },
  textStyles: {
    h1: {
      fontSize: ['sm', 'md', 'xl', '2xl'],
      fontWeight: 'bold',
      letterSpacing: '-2%',
    },
    h2: {
      fontWeight: 'extrabold',
      fontSize: ['sm', 'md', 'xl', '3xl'],
      letterSpacing: 'wide',
      bgGradient: 'linear(to-l, cyan.700,teal.700)',
      bgClip: 'text',
    },
    questionText: {
      fontWeight: 'bold',
      fontSize: 'xl',
      letterSpacing: 'wide',
    },
    questionTextColor: {
      color: 'red',
      fontWeight: 'bold',
      fontSize: 'xl',
      letterSpacing: 'wide',
    },
    text: {
      my: '4',
      fontWeight: 'semibold',
      fontSize: 'md',
      letterSpacing: 'wide',
    },
  },
})
