// Data from dummyjson

export type Products = typeof data
export type Product = (typeof data)[number]
export type ProductWithoutTitle = Omit<Product, 'title'>
export type ProductWithoutPrice = Omit<Product, 'price'>
export type ProductWithoutBrand = Omit<Product, 'brand'>
export type ProductWithoutCategory = Omit<Product, 'category'>

export const headers = ['title', 'price', 'brand', 'category']

export const data = [
  {
    id: 1,
    title: 'iPhone 9',
    price: 549,
    brand: 'Apple',
    category: 'smartphones',
  },
  {
    id: 2,
    title: 'iPhone X',
    price: 899,
    brand: 'Apple',
    category: 'smartphones',
  },
  {
    id: 3,
    title: 'Samsung Universe 9',
    price: 1249,
    brand: 'Samsung',
    category: 'smartphones',
  },
  {
    id: 4,
    title: 'OPPOF19',
    price: 280,
    brand: 'OPPO',
    category: 'smartphones',
  },
  {
    id: 5,
    title: 'Huawei P30',
    price: 499,
    brand: 'Huawei',
    category: 'smartphones',
  },
  {
    id: 6,
    title: 'MacBook Pro',
    price: 1749,
    brand: 'Apple',
    category: 'laptops',
  },
  {
    id: 7,
    title: 'Samsung Galaxy Book',
    price: 1499,
    brand: 'Samsung',
    category: 'laptops',
  },
  {
    id: 8,
    title: 'Microsoft Surface Laptop 4',
    price: 1499,
    brand: 'Microsoft Surface',
    category: 'laptops',
  },
  {
    id: 9,
    title: 'Infinix INBOOK',
    price: 1099,
    brand: 'Infinix',
    category: 'laptops',
  },
  {
    id: 10,
    title: 'HP Pavilion 15-DK1056WM',
    price: 1099,
    brand: 'HP Pavilion',
    category: 'laptops',
  },
  {
    id: 11,
    title: 'perfume Oil',
    price: 13,
    brand: 'Impression of Acqua Di Gio',
    category: 'fragrances',
  },
  {
    id: 12,
    title: 'Brown Perfume',
    price: 40,
    brand: 'Royal_Mirage',
    category: 'fragrances',
  },
  {
    id: 13,
    title: 'Fog Scent Xpressio Perfume',
    price: 13,
    brand: 'Fog Scent Xpressio',
    category: 'fragrances',
  },
  {
    id: 14,
    title: 'Non-Alcoholic Concentrated Perfume Oil',
    price: 120,
    brand: 'Al Munakh',
    category: 'fragrances',
  },
  {
    id: 15,
    title: 'Eau De Perfume Spray',
    price: 30,
    brand: 'Lord - Al-Rehab',
    category: 'fragrances',
  },
  {
    id: 16,
    title: 'Hyaluronic Acid Serum',
    price: 19,
    brand: "L'Oreal Paris",
    category: 'skincare',
  },
  {
    id: 17,
    title: 'Tree Oil 30ml',
    price: 12,
    brand: 'Hemani Tea',
    category: 'skincare',
  },
  {
    id: 18,
    title: 'Oil Free Moisturizer 100ml',
    price: 40,
    brand: 'Dermive',
    category: 'skincare',
  },
  {
    id: 19,
    title: 'Skin Beauty Serum.',
    price: 46,
    brand: 'ROREC White Rice',
    category: 'skincare',
  },
  {
    id: 20,
    title: 'Freckle Treatment Cream- 15gm',
    price: 70,
    brand: 'Fair & Clear',
    category: 'skincare',
  },
  {
    id: 21,
    title: '- Daal Masoor 500 grams',
    price: 20,
    brand: 'Saaf & Khaas',
    category: 'groceries',
  },
  {
    id: 22,
    title: 'Elbow Macaroni - 400 gm',
    price: 14,
    brand: 'Bake Parlor Big',
    category: 'groceries',
  },
  {
    id: 23,
    title: 'Orange Essence Food Flavou',
    price: 14,
    brand: 'Baking Food Items',
    category: 'groceries',
  },
  {
    id: 24,
    title: 'cereals muesli fruit nuts',
    price: 46,
    brand: 'fauji',
    category: 'groceries',
  },
  {
    id: 25,
    title: 'Gulab Powder 50 Gram',
    price: 70,
    brand: 'Dry Rose',
    category: 'groceries',
  },
  {
    id: 26,
    title: 'Plant Hanger For Home',
    price: 41,
    brand: 'Boho Decor',
    category: 'home-decoration',
  },
  {
    id: 27,
    title: 'Flying Wooden Bird',
    price: 51,
    brand: 'Flying Wooden',
    category: 'home-decoration',
  },
  {
    id: 28,
    title: '3D Embellishment Art Lamp',
    price: 20,
    brand: 'LED Lights',
    category: 'home-decoration',
  },
  {
    id: 29,
    title: 'Handcraft Chinese style',
    price: 60,
    brand: 'luxury palace',
    category: 'home-decoration',
  },
  {
    id: 30,
    title: 'Key Holder',
    price: 30,
    brand: 'Golden',
    category: 'home-decoration',
  },
  {
    id: 31,
    title: 'Mornadi Velvet Bed',
    price: 40,
    brand: 'Furniture Bed Set',
    category: 'furniture',
  },
  {
    id: 32,
    title: 'Sofa for Coffe Cafe',
    price: 50,
    brand: 'Ratttan Outdoor',
    category: 'furniture',
  },
  {
    id: 33,
    title: '3 Tier Corner Shelves',
    price: 700,
    brand: 'Kitchen Shelf',
    category: 'furniture',
  },
  {
    id: 34,
    title: 'Plastic Table',
    price: 50,
    brand: 'Multi Purpose',
    category: 'furniture',
  },
  {
    id: 35,
    title: '3 DOOR PORTABLE',
    price: 41,
    brand: 'AmnaMart',
    category: 'furniture',
  },
  {
    id: 36,
    title: 'Sleeve Shirt Womens',
    price: 90,
    brand: 'Professional Wear',
    category: 'tops',
  },
  {
    id: 37,
    title: 'ank Tops for Womens/Girls',
    price: 50,
    brand: 'Soft Cotton',
    category: 'tops',
  },
  {
    id: 38,
    title: 'sublimation plain kids tank',
    price: 100,
    brand: 'Soft Cotton',
    category: 'tops',
  },
  {
    id: 39,
    title: 'Women Sweaters Wool',
    price: 600,
    brand: 'Top Sweater',
    category: 'tops',
  },
  {
    id: 40,
    title: 'women winter clothes',
    price: 57,
    brand: 'Top Sweater',
    category: 'tops',
  },
  {
    id: 41,
    title: 'NIGHT SUIT',
    price: 55,
    brand: 'RED MICKY MOUSE..',
    category: 'womens-dresses',
  },
  {
    id: 42,
    title: 'Stiched Kurta plus trouser',
    price: 80,
    brand: 'Digital Printed',
    category: 'womens-dresses',
  },
  {
    id: 43,
    title: 'frock gold printed',
    price: 600,
    brand: 'Ghazi Fabric',
    category: 'womens-dresses',
  },
  {
    id: 44,
    title: 'Ladies Multicolored Dress',
    price: 79,
    brand: 'Ghazi Fabric',
    category: 'womens-dresses',
  },
  {
    id: 45,
    title: 'Malai Maxi Dress',
    price: 50,
    brand: 'IELGY',
    category: 'womens-dresses',
  },
  {
    id: 46,
    title: "women's shoes",
    price: 40,
    brand: 'IELGY fashion',
    category: 'womens-shoes',
  },
  {
    id: 47,
    title: 'Sneaker shoes',
    price: 120,
    brand: 'Synthetic Leather',
    category: 'womens-shoes',
  },
  {
    id: 48,
    title: 'Women Strip Heel',
    price: 40,
    brand: 'Sandals Flip Flops',
    category: 'womens-shoes',
  },
  {
    id: 49,
    title: 'Chappals & Shoe Ladies Metallic',
    price: 23,
    brand: 'Maasai Sandals',
    category: 'womens-shoes',
  },
  {
    id: 50,
    title: 'Women Shoes',
    price: 36,
    brand: 'Arrivals Genuine',
    category: 'womens-shoes',
  },
  {
    id: 51,
    title: 'half sleeves T shirts',
    price: 23,
    brand: 'Vintage Apparel',
    category: 'mens-shirts',
  },
  {
    id: 52,
    title: 'FREE FIRE T Shirt',
    price: 10,
    brand: 'FREE FIRE',
    category: 'mens-shirts',
  },
  {
    id: 53,
    title: 'printed high quality T shirts',
    price: 35,
    brand: 'Vintage Apparel',
    category: 'mens-shirts',
  },
  {
    id: 54,
    title: 'Pubg Printed Graphic T-Shirt',
    price: 46,
    brand: 'The Warehouse',
    category: 'mens-shirts',
  },
  {
    id: 55,
    title: 'Money Heist Printed Summer T Shirts',
    price: 66,
    brand: 'The Warehouse',
    category: 'mens-shirts',
  },
  {
    id: 56,
    title: 'Sneakers Joggers Shoes',
    price: 40,
    brand: 'Sneakers',
    category: 'mens-shoes',
  },
  {
    id: 57,
    title: 'Loafers for men',
    price: 47,
    brand: 'Rubber',
    category: 'mens-shoes',
  },
  {
    id: 58,
    title: 'formal offices shoes',
    price: 57,
    brand: 'The Warehouse',
    category: 'mens-shoes',
  },
  {
    id: 59,
    title: 'Spring and summershoes',
    price: 20,
    brand: 'Sneakers',
    category: 'mens-shoes',
  },
  {
    id: 60,
    title: 'Stylish Casual Jeans Shoes',
    price: 58,
    brand: 'Sneakers',
    category: 'mens-shoes',
  },
  {
    id: 61,
    title: 'Leather Straps Wristwatch',
    price: 120,
    brand: 'Naviforce',
    category: 'mens-watches',
  },
  {
    id: 62,
    title: 'Waterproof Leather Brand Watch',
    price: 46,
    brand: 'SKMEI 9117',
    category: 'mens-watches',
  },
  {
    id: 63,
    title: 'Royal Blue Premium Watch',
    price: 50,
    brand: 'SKMEI 9117',
    category: 'mens-watches',
  },
  {
    id: 64,
    title: 'Leather Strap Skeleton Watch',
    price: 46,
    brand: 'Strap Skeleton',
    category: 'mens-watches',
  },
  {
    id: 65,
    title: 'Stainless Steel Wrist Watch',
    price: 47,
    brand: 'Stainless',
    category: 'mens-watches',
  },
  {
    id: 66,
    title: 'Steel Analog Couple Watches',
    price: 35,
    brand: 'Eastern Watches',
    category: 'womens-watches',
  },
  {
    id: 67,
    title: 'Fashion Magnetic Wrist Watch',
    price: 60,
    brand: 'Eastern Watches',
    category: 'womens-watches',
  },
  {
    id: 68,
    title: 'Stylish Luxury Digital Watch',
    price: 57,
    brand: 'Luxury Digital',
    category: 'womens-watches',
  },
  {
    id: 69,
    title: 'Golden Watch Pearls Bracelet Watch',
    price: 47,
    brand: 'Watch Pearls',
    category: 'womens-watches',
  },
  {
    id: 70,
    title: 'Stainless Steel Women',
    price: 35,
    brand: 'Bracelet',
    category: 'womens-watches',
  },
  {
    id: 71,
    title: 'Women Shoulder Bags',
    price: 46,
    brand: 'LouisWill',
    category: 'womens-bags',
  },
  {
    id: 72,
    title: 'Handbag For Girls',
    price: 23,
    brand: 'LouisWill',
    category: 'womens-bags',
  },
  {
    id: 73,
    title: 'Fancy hand clutch',
    price: 44,
    brand: 'Bracelet',
    category: 'womens-bags',
  },
  {
    id: 74,
    title: 'Leather Hand Bag',
    price: 57,
    brand: 'Copenhagen Luxe',
    category: 'womens-bags',
  },
  {
    id: 75,
    title: 'Seven Pocket Women Bag',
    price: 68,
    brand: 'Steal Frame',
    category: 'womens-bags',
  },
  {
    id: 76,
    title: 'Silver Ring Set Women',
    price: 70,
    brand: 'Darojay',
    category: 'womens-jewellery',
  },
  {
    id: 77,
    title: 'Rose Ring',
    price: 100,
    brand: 'Copenhagen Luxe',
    category: 'womens-jewellery',
  },
  {
    id: 78,
    title: 'Rhinestone Korean Style Open Rings',
    price: 30,
    brand: 'Fashion Jewellery',
    category: 'womens-jewellery',
  },
  {
    id: 79,
    title: 'Elegant Female Pearl Earrings',
    price: 30,
    brand: 'Fashion Jewellery',
    category: 'womens-jewellery',
  },
  {
    id: 80,
    title: 'Chain Pin Tassel Earrings',
    price: 45,
    brand: 'Cuff Butterfly',
    category: 'womens-jewellery',
  },
  {
    id: 81,
    title: 'Round Silver Frame Sun Glasses',
    price: 19,
    brand: 'Designer Sun Glasses',
    category: 'sunglasses',
  },
  {
    id: 82,
    title: 'Kabir Singh Square Sunglass',
    price: 50,
    brand: 'Designer Sun Glasses',
    category: 'sunglasses',
  },
  {
    id: 83,
    title: 'Wiley X Night Vision Yellow Glasses',
    price: 30,
    brand: 'mastar watch',
    category: 'sunglasses',
  },
  {
    id: 84,
    title: 'Square Sunglasses',
    price: 28,
    brand: 'mastar watch',
    category: 'sunglasses',
  },
  {
    id: 85,
    title: 'LouisWill Men Sunglasses',
    price: 50,
    brand: 'LouisWill',
    category: 'sunglasses',
  },
  {
    id: 86,
    title: 'Bluetooth Aux',
    price: 25,
    brand: 'Car Aux',
    category: 'automotive',
  },
  {
    id: 87,
    title: 't Temperature Controller Incubator Controller',
    price: 40,
    brand: 'W1209 DC12V',
    category: 'automotive',
  },
  {
    id: 88,
    title: 'TC Reusable Silicone Magic Washing Gloves',
    price: 29,
    brand: 'TC Reusable',
    category: 'automotive',
  },
  {
    id: 89,
    title: 'Qualcomm original Car Charger',
    price: 40,
    brand: 'TC Reusable',
    category: 'automotive',
  },
  {
    id: 90,
    title: 'Cycle Bike Glow',
    price: 35,
    brand: 'Neon LED Light',
    category: 'automotive',
  },
  {
    id: 91,
    title: 'Black Motorbike',
    price: 569,
    brand: 'METRO 70cc Motorcycle - MR70',
    category: 'motorcycle',
  },
  {
    id: 92,
    title: 'HOT SALE IN EUROPE electric racing motorcycle',
    price: 920,
    brand: 'BRAVE BULL',
    category: 'motorcycle',
  },
  {
    id: 93,
    title: 'Automatic Motor Gas Motorcycles',
    price: 1050,
    brand: 'shock absorber',
    category: 'motorcycle',
  },
  {
    id: 94,
    title: 'new arrivals Fashion motocross goggles',
    price: 900,
    brand: 'JIEPOLLY',
    category: 'motorcycle',
  },
  {
    id: 95,
    title: 'Wholesale cargo lashing Belt',
    price: 930,
    brand: 'Xiangle',
    category: 'motorcycle',
  },
  {
    id: 96,
    title: 'lighting ceiling kitchen',
    price: 30,
    brand: 'lightingbrilliance',
    category: 'lighting',
  },
  {
    id: 97,
    title: 'Metal Ceramic Flower',
    price: 35,
    brand: 'Ifei Home',
    category: 'lighting',
  },
  {
    id: 98,
    title: '3 lights lndenpant kitchen islang',
    price: 34,
    brand: 'DADAWU',
    category: 'lighting',
  },
  {
    id: 99,
    title: 'American Vintage Wood Pendant Light',
    price: 46,
    brand: 'Ifei Home',
    category: 'lighting',
  },
  {
    id: 100,
    title: 'Crystal chandelier maria theresa for 12 light',
    price: 47,
    brand: 'YIOSI',
    category: 'lighting',
  },
]
