/** @type {import('@remix-run/dev').AppConfig} */

module.exports = {
  ignoredRouteFiles: ['**/.*'],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    'is-reference',
    'periscopic',
    /estree-walker.*/,
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^bail.*/,
    /^trough.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^decode.*/,
    /^character.*/,
    /^property.*/,
    /^space.*/,
    /^comma.*/,
    'is-hexadecimal',
    'is-decimal',
    /^react-markdown$/,
    'is-alphanumerical',
    'trim-lines',
    /^vfile.*/,
    'zwitch',
    /^ccount*/,
    /^markdown-table*/,
    /mdx.*/,
    /vfile.*/,
    /unified.*/,
    /estree-util-.*/,
    'hast-util-to-estree',
    /estree-util-.*/,
    'parse-entities',
    /remark.*/,
    'stringify-entities',
    /micromark-.*/,
    /mdast-.*/,
    'ccount',
    /unist-.*/,
    'rehype-highlight',
    'hast-util-to-text',
    'mdx-bundler',
    'lowlight',
    'hast-util-is-element',
    'fault',
    'decode-named-character-reference',
    'character-entities',
    'markdown-table',
  ],
}
